#!/usr/local/bin/python3

import pyvisa as pv
import time
import sys, getopt
from file_io import *

# filename = "../Blinkenmatrix/opfiles/memorydelta.bcm"
filename = ""
# filename = "./linktest.lut"
lines_per_batch = 512
show_addresses = False
isv_menu = True

argv = sys.argv[1:]

try:
	opts, args = getopt.getopt(argv,"hi:a", [])
except getopt.GetoptError:
	print("lutup 			(Use -h for help)")
	sys.exit(2)
for opt, arg in opts:
	if opt == '-h':
		print("Blinkenrechner Project CPU Lookup-Table Uploader")
		print("")
		print("Usage:")
		print("  lutup ")
		print("  lutup ... -i <file>")
		print("  lutup ... -h")
		print("  lutup ... -a")
		print("")
		print("Description")
		print("  -i  File to upload. If not specified, menu to select version from archive")
		print("      will be run.")
		print("  -h  Show help")
		print("  -a  Show addresses")
		sys.exit()
	elif opt == "-i":
		filename = arg
		isv_menu = False
	elif opt == "-a":
		show_addresses = True

# Open ISV menu if prompted
if isv_menu:
	# Read quark configuration
	conf = dict()
	status = load_conf("/Users/grantgiesbrecht/Documents/GitHub/Quark/quark.conf", conf)
	if status == 0:
		print(f"{Fore.RED}ERROR: Failed to find quark.conf{Style.RESET_ALL}")

	# Scan ISV Archive
	all_isv = get_all_ISV(conf["Archive_Dir"])

	# Run selector menu
	series_name, ver_tuple = get_isv_menu(all_isv)

	# Get full path to comparison file
	filename = full_path_lut(conf["Archive_Dir"], series_name, ver_tuple)
	print(f"Uploading LUT file at path:\n\t{Fore.BLUE}{filename}{Style.RESET_ALL}")

t_upload = []
t_write = []

port = "FIRST"; # Options: BACK_LEFT, FRONT_LEFT, BACK_RIGHT, FRONT_RIGHT, FIRST

#Open connection to Arduino
rm = pv.ResourceManager()
addr = "INVALID"
try:
	addr_list = rm.list_resources()
	if show_addresses:
		print("Detected Addresses:")
		for ad in addr_list:
			print(f"\t{ad}")
		print("")
	if port == "FIRST":
		for ad in addr_list:
			if not ("BLTH"  in ad or "tooth" in ad):
				addr = ad
		# addr = rm.list_resources()[1]
	else:
		for ad in addr_list:
			if port == "BACK_LEFT":
				if '14401' in ad:
					addr = ad
			elif port == "FRONT_LEFT":
				if '14301' in ad:
					addr = ad
			elif port == "FRONT_RIGHT":
				if '14201' in ad:
					addr = ad
			elif port == "BACK_RIGHT":
				if '14101' in ad:
					addr = ad

	if addr == "INVALID":
		print(f"Failed to find requested address at location '{port}'")
		exit()

	dev = rm.open_resource(addr, baud_rate = 115200)
	# dev = rm.open_resource(addr)
	# dev.baud_rate = 115200
except Exception as e:
	print(f"Failed to open device at address '{addr}'")
	print(str(e))
	exit()
# dev.timeout = 25e3 #Timeout in ms

#Print messages
print(f"Aquired device resource.\n\tAddress: \"{addr}\"")
print("Waiting to connect", end="", flush=True)

#Send messages to device and wait until it responds...
connected = False
for i in range(10):

	dev.timeout = 1e3
	dev.write("T")
	try:
		dev.read()
	except pv.errors.VisaIOError:
		print('.', end="", flush=True)
	else:
		connected = True
		print("Connection verified - continuing\n")
		break;
if not connected:
	print("\nFailed to verify connection. Exiting.")
	exit()

#Read messages from the device just to make sure the buffer is clear
print("Clearing buffer", end="", flush=True)
num_reads = 0;
while (True):
	try:
		dev.read()
	except pv.errors.VisaIOError:
		break;
	else:
		num_reads += 1;
if num_reads == 0:
	print(" \t\tNothing to clear. Continuing")
else:
	print(f" \t\tCleared {num_reads} messages")

#Set timeout to be longer
dev.timeout = 3e3 #ms

print(f"\nUploading file: {filename}")

#Open file
line_count = 0
batch_no = -1
wrote_set = False
with open(filename, 'r') as f:

	start = time.time()

	#For each line
	for line in f:

		batch_no += 1

		wrote_set = False

		line = line.strip('\n')

		#Send line to Arduino
		print(f"Sending '{line}' \t\t", end="", flush=True)
		dev.write(f"{line}*")
		recd = dev.read().strip("\n").strip('\r')

		#This double checks that there aren't some stray special chars in string
		orig_len = len(recd)
		recd = recd.replace('\n', '')
		recd = recd.replace('\r', '')
		had_bad = False
		if (orig_len != len(recd)):
			had_bad = True

		if recd == "G":
			if (had_bad):
				print("!", end='')
			print("Good")
		else:
			if (had_bad):
				print("!", end='')
			print(f"? \t'{recd}'")

		#Wait for Arduino to sync if neccesary
		line_count += 1;



		if line_count >= lines_per_batch:

			wrote_set = True
			t_upload.append(time.time() - start)
			start = time.time()

			t_last = t_upload[-1]
			print(f"Batch {batch_no} sent. ({line_count} lines in {round(t_last, 3)} sec)")
			print("Waiting for data write to be complete")

			print('\n|           | (* = 50 Bytes written)\r|', end='', flush=True);
			while(True):

				recd = dev.read().strip('\n').strip('\r')
				if recd == "Ready":
					print("\nWrite complete. Sending next batch of data\n")
					break;
				elif recd == "U":
					print("*", end='', flush=True)
				else:
					print("?", end='', flush=True)


			line_count = 0;
			t_write.append(time.time()-start)
			start = time.time()

# If an odd number of upload cycles occured, force a write and monitor it here
if (not wrote_set):
	dev.write("END*")

	t_upload.append(time.time() - start)
	start = time.time()

	t_last = t_upload[-1]
	print(f"Batch {batch_no} sent. ({line_count} lines in {round(t_last, 3)} sec)")
	print("Waiting for data write to be complete")

	print('\n|           | (* = 50 Bytes written)\r|', end='', flush=True);
	while(True):

		recd = dev.read().strip('\n').strip('\r')
		if recd == "Ready":
			print("\nWrite complete. Sending next batch of data\n")
			break;
		elif recd == "U":
			print("*", end='', flush=True)
		elif recd == "U":
			print("X", end='', flush=True)
		else:
			print(f"?>{recd}<", end='', flush=True)

	t_write.append(time.time()-start)

#Print summary data

print("Upload to Arduino times:")
for num, t in enumerate(t_upload):
	print(f"\t{num}: {round(t, 3)} sec")

print("Write to chip times:")
for num, t in enumerate(t_write):
	print(f"\t{num}: {round(t, 3)} sec")
